FROM ghcr.io/home-assistant/base:latest

ENV LANG C.UTF-8

RUN apk update
RUN apk add --no-cache nodejs npm python3 linux-headers py3-pip alpine-sdk libcap bluez bluez-dev eudev-dev
RUN setcap cap_net_raw+eip $(eval readlink -f $(which node))

WORKDIR /

COPY start.sh /app/start.sh
RUN chmod 755 /app/start.sh

COPY addon /app
RUN rm -rf /app/node_modules

RUN cd /app && npm i

# here we should just copy the /app contents to a run image with nodejs and other requirements only

ENTRYPOINT ["/app/start.sh"]

LABEL io.hass.version="VERSION" io.hass.type="addon" io.hass.arch="armhf|aarch64|i386|amd64"
